name: CI-CD   # 工作流名称，可随意改

# 触发条件：每次 push 到 main 分支就执行
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取源码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 打 jar 包（Maven 示例，如果你本地已打好可跳过）
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build jar with Maven
        run: mvn -B package -DskipTests

      # 3. 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build --build-arg JAR_FILE=target/youlai-boot.jar -t youli-app .

      # 4. 保存镜像为 tar（方便 scp）
      - name: Save image as tar
        run: docker save youli-app > youli-app.tar

      # 5. 把镜像拷到服务器
      - name: Copy image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "youli-app.tar"
          target: "/tmp"

      # 6. 在服务器上加载并运行
      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker load < /tmp/youli-app.tar
            docker stop youli-app || true
            docker rm   youli-app || true
            docker run -d --restart=unless-stopped \
                       --name youli-app \
                       -p 8989:8989 \
                       youli-app
